---
- name: Include OS-Specific variables
    include_vars: "{{ ansible_os_family }}.yml"

- include: packages-redhat.yml
    when: ansible_os_family == "RedHat"

- include: packages-debian.yml
    when: ansible_os_family == "Debian"

- name: Disabling SELinux
    selinux: state=disabled
    when: ansible_os_family == "RedHat"

- name: Adding entry to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^{{ ansible_default_ipv4.address }} {{ ansible_hostname }}$"
      line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"

- include: install.yml
#  include: configure.yml
#  include: service.yml

